- name: demo for functions/filters
  hosts: local
  connection: local
  tasks:
  - name: print the default varaiable value
    ansible.builtin.debug:
      msg: "Hello, {{ NAME | default('ram') }}"

  - name: convert to upper
    vars:
      greeting: "Hello rAm"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lower
    vars:
      greeting: "Hello rAm"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,2,3,4,5,6,7,8,9,0,0,9,8,7,6,5,4,3,2,1]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the mini and max values
    vars:
      numbers: [1,2,3,4,5,6,7,8,9,0]
    ansible.builtin.debug:
      msg: "MIN: {{ numbers | min }},MAX: {{ numbers | max }}"

  - name: converting dic/map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "siva"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: converting dic/map to list
    vars:
      course:
        - { "key": "name","value": "DevOps with AWS" }
        - { "key": "duration","value": 120 }
        - { "key": "trainer","value": "siva"}
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"